server:
  port: 8082

spring:
  application:
    name: profile-collector
  config:
    import: nacos://127.0.0.1:8848
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        enabled: true
      username: nacos
      password: nacos

collector:
  kafka:
    bootstrapServers: localhost:9092
    topic: realtime-events
  redis:
    host: localhost
    port: 6379
  ods:
    file: ./tmp/ad-events.log

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true
